apiVersion: skaffold/v2beta26
kind: Config
metadata:
  name: hello
build:
  artifacts:
  - image: hello
    context: hello
    docker:
      dockerfile: Dockerfile    
    sync:
      auto: true      
deploy:
  kustomize:
    paths:
      - deployments/overlays/dev
profiles:
  - name: dev
    deploy:
      kustomize:
        paths:
          - deployments/overlays/dev
  - name: test
    deploy:
      kustomize:
        paths:
          - deployments/overlays/test
  - name: prod
    deploy:
      kustomize:
        paths:
          - deployments/overlays/prod
portForward:
- resourceType: deployment
  resourceName: hello
  port: 8080