apiVersion: skaffold/v2beta26
kind: Config
metadata:
  name: hello
build:
  artifacts:
  - image: hello
    context: hello
    docker:
      dockerfile: Dockerfile
manifests:
  kustomize:
    paths:
    - deployments/overlays/dev
profiles:
- name: base
  manifests:
    kustomize:
      paths:
      - deployments/base
- name: prod
  manifests:
    kustomize:
      paths:
      - deployments/overlays/prod
- name: test
  manifests:
    kustomize:
      paths:
      - deployments/overlays/test
portForward:
- resourceType: deployment
  resourceName: hello
  port: 8080
