name: publish

on:  
  push:
    tags:
      - 'v*.*.*'

env:
  # there is nothing secret really here so don't bother with changing this GHA secret
  KEY: gcpkms://projects/cloudy-demos/locations/us-west1/keyRings/github-actions/cryptoKeys/builder/cryptoKeyVersions/1
  
jobs:

  # this will unit test, lint, and scan for vulnerabilities 
  test:
    uses: ./.github/workflows/test-on-call.yaml
    secrets:
      token: ${{ secrets.SNYK_TOKEN }}

  push:
    runs-on: ubuntu-latest
    needs: test
    permissions:
      contents: read
      id-token: write
    # TODO: implement outputs in the ko publish steps
    # outputs:
    #   app: ${{ steps.pub-app.outputs.sha }}
    #   worker: ${{ steps.pub-worker.outputs.sha }}
    steps:

    - name: Setup Go
      uses: actions/setup-go@v3
      with:
        go-version: '1.19.4'
    - run: go version

    - name: Cache Go Modules
      uses: actions/cache@v3
      with:
        path: |
          ~/.cache/go-build
          ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-

    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Capture Variables
      run: |
        echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      
    - id: auth
      name: Get GCP token
      uses: google-github-actions/auth@v1
      with:
          token_format: "access_token"
          # some may consider project number and service account name to be private, 
          # move to GHA secrets if that's the case.
          workload_identity_provider: projects/799736955886/locations/global/workloadIdentityPools/github-pool/providers/github-provider
          service_account: github-actions-user@cloudy-demos.iam.gserviceaccount.com

    - name: Install Ko
      uses: imjasonh/setup-ko@v0.6
        
    - name: Login With ko
      run: |
        ko version
        ko login gcr.io \
          --username=oauth2accesstoken \
          --password=${{ steps.auth.outputs.access_token }}

    - name: Tidy Modules
      run: |
        make tidy

    - id: publish
      name: Publish Image
      run: |
        ko build . --image-refs ./image-digest --bare --tags ${{ env.RELEASE_VERSION }},latest
      env:
        KO_DOCKER_REPO: us-west1-docker.pkg.dev/cloudy-demos/hello-gha/hello
        GOFLAGS: "-ldflags=-X=main.version=${{ env.RELEASE_VERSION }}"

    - name: Install Cosign
      uses: sigstore/cosign-installer@main
      with:
        cosign-release: 'v1.13.1'

    - name: Login With cosign
      run: |
        cosign version
        cosign login us-west1-docker.pkg.dev \
          --username=oauth2accesstoken \
          --password=${{ steps.auth.outputs.access_token }}

    - name: Sign Image
      run: |
        cosign generate-key-pair --kms ${{ env.KEY }}
        cosign sign --key ${{ env.KEY }} \
          -a "version=${{ env.RELEASE_VERSION }}" \
          -a "commit=${{ env.RELEASE_VERSION }}" \
          $(cat ./image-digest)
        cosign verify --key ${{ env.KEY }} $(cat ./image-digest)
      env:
        COSIGN_EXPERIMENTAL: 1
