name: image

on:
  workflow_call:

jobs:

  image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
    - name: Setup Go
      uses: actions/setup-go@v3
      with:
        go-version: ${{ env.GO_VERSION }}
    - run: go version
    - name: Cache Modules
      uses: actions/cache@v3
      with:
        path: |
          ~/.cache/go-build
          ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-
    - name: Checkout Code
      uses: actions/checkout@v3
    - name: Tidy Modules
      run: |
        make tidy
    - name: Capture Variables
      run: |
        echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
    - id: auth
      name: Get GCP token
      uses: google-github-actions/auth@v1
      with:
          token_format: "access_token"
          workload_identity_provider: ${{ env.ID_PROVIDER }}
          service_account: ${{ env.SERVICE_ACCOUNT }}
    - name: Define Metadata
      id: meta
      uses: docker/metadata-action@v4
      with:
        images: |
          ${{ env.IMAGE }}
        tags: |
          type=raw,enable=true,value=${{ env.RELEASE_VERSION }}
          type=raw,enable=true,value=${{ env.GITHUB_SHA }}
    - name: Registry Auth
      uses: docker/login-action@v2
      with:
        registry: ${{ env.REGISTRY }}
        username: oauth2accesstoken
        password: ${{ steps.auth.outputs.access_token }}
    - name: Image Push
      id: push
      uses: docker/build-push-action@v3
      with:
        platforms: linux/amd64
        context: .
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
    - name: Print Digest
      run: |
        echo ${{ steps.push.outputs.digest }}
    
    outputs:
      digest: ${{ steps.push.outputs.digest }}
