name: image

on:
  workflow_call:
    secrets:

env:
  PROVIDER: projects/799736955886/locations/global/workloadIdentityPools/github-pool/providers/github-provider
  ACCOUNT: github-actions-user@cloudy-demos.iam.gserviceaccount.com
  REGISTRY: us-west1-docker.pkg.dev
  IMAGE: us-west1-docker.pkg.dev/cloudy-demos/hello-gha/hello

jobs:
  image:
    runs-on: ubuntu-latest
    needs: test
    permissions:
      contents: read
      id-token: write
    steps:
    - name: Setup Go
      uses: actions/setup-go@v3
      with:
        go-version: '1.19.4'
    - run: go version
    - name: Cache Modules
      uses: actions/cache@v3
      with:
        path: |
          ~/.cache/go-build
          ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-
    - name: Checkout Code
      uses: actions/checkout@v3
    - name: Tidy Modules
      run: |
        make tidy
    - name: Capture Variables
      run: |
        echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
    - id: auth
      name: Get GCP token
      uses: google-github-actions/auth@v1
      with:
          token_format: "access_token"
          workload_identity_provider: ${{ env.PROVIDER }}
          service_account: ${{ env.ACCOUNT }}
    - name: Define Metadata
      id: meta
      uses: docker/metadata-action@v4
      with:
        images: |
          ${{ env.IMAGE }}
        tags: |
          type=raw,enable=true,value=${{ env.RELEASE_VERSION }}
          type=raw,enable=true,value=${{ env.GITHUB_SHA }}
    - name: Registry Auth
      uses: docker/login-action@v2
      with:
        registry: ${{ env.REGISTRY }}
        username: oauth2accesstoken
        password: ${{ secrets.token }}
    - name: Image Push
      id: push
      uses: docker/build-push-action@v3
      with:
        platforms: linux/amd64
        context: .
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
    
    outputs:
      token: ${{ steps.auth.outputs.access_token }}
      digest: ${{ env.IMG }}@${{ steps.push.outputs.digest }}
