name: publish

on:  
  push:
    tags:
      - 'v*.*.*'

env:
  KEY: gcpkms://projects/cloudy-demos/locations/us-west1/keyRings/github-actions/cryptoKeys/signer/cryptoKeyVersions/1
  PROVIDER: projects/799736955886/locations/global/workloadIdentityPools/github-pool/providers/github-provider
  ACCOUNT: github-actions-user@cloudy-demos.iam.gserviceaccount.com
  REGISTRY: us-west1-docker.pkg.dev
  IMAGE: us-west1-docker.pkg.dev/cloudy-demos/hello-gha/hello
  GO_VERSION: "1.19.4"
  
jobs:

  test:
    uses: ./.github/workflows/test.yaml
    secrets:
      token: ${{ secrets.SNYK_TOKEN }}
    with:
      go_version: ${{ env.GO_VERSION }}

  image:
    uses: ./.github/workflows/image.yaml
    needs: test
    with:
      go_version: ${{ env.GO_VERSION }}
      registry: ${{ env.REGISTRY }}
      image: ${{ env.IMAGE }}
      id_provider: ${{ env.PROVIDER }}
      service_account: ${{ env.ACCOUNT }}

  sign:
    uses: ./.github/workflows/sign.yaml
    needs: image
    with:
      registry: ${{ env.REGISTRY }}
      id_provider: ${{ env.PROVIDER }}
      service_account: ${{ env.ACCOUNT }}
      digest: ${{ needs.image.output.digest }}
      key: ${{ env.KEY }}
