name: publish

on:  
  push:
    tags:
      - 'v*.*.*'
  
jobs:

  test:
    uses: ./.github/workflows/test.yaml
    secrets:
      token: ${{ secrets.SNYK_TOKEN }}

  image:
    uses: ./.github/workflows/image.yaml
    needs: test
    with:
      registry: ${{ secrets.REGISTRY_URI }}
      image: ${{ secrets.REGISTRY_URI }}/${{ secrets.REGISTRY_NAME }}/hello
      id_provider: ${{ secrets.ID_PROVIDER }}
      service_account: ${{ secrets.SERVICE_ACCOUNT }}

  sign:
    uses: ./.github/workflows/sign.yaml
    needs: image
    with:
      registry: ${{ secrets.REGISTRY_URI }}
      id_provider: ${{ secrets.ID_PROVIDER }}
      service_account: ${{ secrets.SERVICE_ACCOUNT }}
      digest: ${{ needs.image.outputs.digest }}
      key: ${{ secrets.KEY }}


# Example Secrets Values
# ======================
# KEY: gcpkms://projects/cloudy-demos/locations/us-west1/keyRings/github-actions/cryptoKeys/signer/cryptoKeyVersions/1
# ID_PROVIDER: projects/799736955886/locations/global/workloadIdentityPools/github-pool/providers/github-provider
# SERVICE_ACCOUNT: github-actions-user@cloudy-demos.iam.gserviceaccount.com
# REGISTRY_URI: us-west1-docker.pkg.dev
# REGISTRY_NAME: cloudy-demos/hello-gha