name: sign

on:
  workflow_call:
    secrets:
      token:
        required: true
      digest:
        required: true

env:
  # there is nothing secret really here so don't bother with changing this GHA secret
  KEY: gcpkms://projects/cloudy-demos/locations/us-west1/keyRings/github-actions/cryptoKeys/signer/cryptoKeyVersions/1
      
jobs:

  push:
    runs-on: ubuntu-latest
    needs: image
    permissions:
      contents: read
      id-token: write
    steps:
    - name: Install Cosign
      uses: sigstore/cosign-installer@main
      with:
        cosign-release: 'v1.13.1'
    - name: Auth Cosign
      run: |
        cosign version
        cosign login us-west1-docker.pkg.dev --username=oauth2accesstoken --password=${{ secrets.token }}
    - name: Get KMS Key
      run: |
        cosign generate-key-pair --kms ${{ env.KEY }}
    - name: Sign Image
      run: |
        cosign sign --force --key ${{ env.KEY }} {{ secrets.digest }}
      env:
        COSIGN_PASSWORD: ${{ secrets.token }}
