name: sign

on:
  workflow_call:
    inputs:
      digest:
        description: 'Image name with the SHA digest of the published image'
        required: true
        type: string
      cosign_version:
        description: 'Version of Cosign to use for signing'
        default: v1.13.1
        required: false
        type: string

jobs:

  sign:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
    - name: Print Digest
      run: |
        echo ${{ inputs.digest }}
    - id: auth
      name: Get GCP token
      uses: google-github-actions/auth@v1
      with:
          token_format: "access_token"
          workload_identity_provider: ${{ env.ID_PROVIDER }}
          service_account: ${{ env.SERVICE_ACCOUNT }}
    - name: Install Cosign
      uses: sigstore/cosign-installer@main
      with:
        cosign-release: ${{ inputs.cosign_version }}
    - name: Auth Cosign
      run: |
        cosign version
        cosign login ${{ env.REGISTRY }} --username=oauth2accesstoken --password=${{ steps.auth.outputs.access_token }}
    - name: Get KMS Key
      run: |
        cosign generate-key-pair --kms ${{ env.KEY }}
    - name: Sign Image
      run: |
        cosign sign --force --key ${{ env.KEY }} ${{ inputs.digest }}
      env:
        COSIGN_PASSWORD: ${{ steps.auth.outputs.access_token }}
