name: push

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  
jobs:

  test:
    uses: ./.github/workflows/test-on-call.yaml
    secrets:
      token: ${{ secrets.SNYK_TOKEN }}